meta-sdk: qt5: fix error for the packagegroup-qt5-imx recipe
After oe-core/5bf3e447d2f5064495d83a8fad30229bcf1ecc9b change allarch
packagegroups are sanity checked. Nativesdk packagegroups should be
excluded for that check, add workaround to avoid errors: "An allarch
packagegroup shouldn't depend on packages which are dynamically renamed

In particular the following error appear during the build:

ERROR: packagegroup-qt5-imx-1.0-r0 do_package_write_deb: An allarch
packagegroup shouldn't depend on packages which are dynamically
renamed (libxkbcommon to libxkbcommon0)i

Let's fix this by the following workaround.

References:
 - https://lists.openembedded.org/g/openembedded-core/message/158230
 - https://codereview.qt-project.org/c/yocto/meta-qt6/+/381703
 - https://gerrit.automotivelinux.org/gerrit/c/AGL/meta-agl-devel/+/27974/1

Signed-off-by: Tommaso Merciai <tomm.merciai@gmail.com>